version: '3.7'
# Most of these values should come from the .env file.

services:
  # User App
  # web:

  # Django API
  api:
    build: ./api
    # only use this command in non-production envs
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - ${API_PORT}:8000
    env_file:
      - ./.env
    networks:
      - dod-network
    depends_on:
      - db
    
  # DB administration tool
  adminer:
    image: adminer
    restart: always
    ports:
      - ${DB_ADMIN_PORT}:8080
    networks:
      - dod-network
  
  # Postgres DB
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    ports:
      - ${SQL_PORT}:5432
    networks:
      - dod-network

# Docker Networks
networks:
  dod-network:
    driver: bridge

# Save the data when containers are shut down
volumes:
  postgres_data: